server:
  port: 8090

spring:

  application:
    name: outbox-service

  datasource:
    url: jdbc:postgresql://localhost:5439/outbox_db
    username: postgres
    password: pAskal123

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.aleks.outbox: DEBUG
