server:
  port: 8084

product-service:
  url: http://localhost:8082

spring:

  application:
    name: order-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
          jwk-set-uri: http://localhost:8079/.well-known/jwks.json

  datasource:
    url: jdbc:postgresql://localhost:5436/order_db
    username: postgres
    password: pAskal123

  jpa:
    hibernate:
      ddl-auto: update

  kafka:

    bootstrap-servers: localhost:29092

    admin:
      auto-create: true

    properties:

      schema.registry.url: http://localhost:8087
      specific.avro.reader: true

    producer:

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:

      group-id: product-group

      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: TRACE